- name: setup prompt
  ansible.builtin.shell: set-prompt runner-machine

- name: create directory
  ansible.builtin.file:
    path: /actions-runner
    state: directory

- name: Download and extract Runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz
    dest: "/actions-runner"
    remote_src: yes

