- name: setup prompt
  ansible.builtin.shell: set-prompt runner-machine

- name: create directory
  ansible.builtin.file:
    path: /actions-runner
    state: directory

- name: Download and extract Runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz
    dest: "/actions-runner"
    remote_src: yes


- name: Download and extract Runner
  ansible.builtin.get_url:
    src: https://cli.github.com/packages/rpm/gh-cli.repo
    dest: /etc/yum/repos.d/gh-cli.repo

- name: install github cli
  ansible.builtin.dnf:
    name: gh-cli
    state: latest





