ame: provision tool

on:
  - workflow_dispatch

jobs:
  provision:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize Terraform
        run: terraform init


